# Generated by Django 2.2.5 on 2019-12-04 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 23, 35, 41, 592035))),
            ],
        ),
    ]
